#!/bin/bash

## Dieses Skript normalisiert Audio-Dateien auf - 2 dB
## sox mit mp3-Support muss installiert sein: sudo apt-get install sox
#
# This script normalize audio files.
#
# Install in ~/.gnome2/nautilus-scripts or ~/Nautilus/scripts
# You need to be running Nautilus 1.0.3+ to use scripts.
# Install in ~/.gnome2/nautilus-scripts or ~/Nautilus/scripts
# You need to be running Nautilus 1.0.3+ to use scripts.
#
# To install as nautilus-script, type:
# sudo cp normalize_to_2.sh /usr/share/nautilus-scripts
# sudo chmod +x /usr/share/nautilus-scripts/normalize_to_2.sh
# sudo ln -s /usr/share/nautilus-scripts/normalize_to_2.sh ~/.gnome2/nautilus-scripts/normalize_to_2
#
# dependent on: sox, libsox-fmt-mp3
# if not alraedy on your system, type for example:
# sudo apt-get install sox libsox-fmt-mp3
# 
#
#         
# Author: Joerg Sorge
# Distributed under the terms of GNU GPL version 2 or later
# Copyright (C) Joerg Sorge joergsorge @ g mail 
# 2017-03-29

function f_check_package () {
	package_install=$1
	if dpkg-query -s $1 2>/dev/null|grep -q installed; then
		echo "$package_install installiert"
	else
		zenity --error --text="Paket $package_install ist nicht installiert, Bearbeitung nicht moeglich." 
		exit
	fi
}

echo -n "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | while read file ; do

report "normalizer"
(

	# check for packages
	f_check_package "sox"
	f_check_package "libsox-fmt-mp3"
	filename=$(basename "$file")
	extension="${filename##*.}"
	# echo and progress will pulsate
	echo "10"
	echo "# Bearbeitung ...\n$filename"
	
	# copy original file in to subfolder
	mkdir -p original
	path_source=$(dirname "$file")
	file_path_orig="$path_source/original/$filename"
	cp "$file" "$file_path_orig"
	echo "# Normalisieren von\n$filename"
	meldung=$(sox "$file_path_orig" --norm=-2 "$file" 2>&1 && echo "Ohne_Fehler_beendet")
	# alle zeichen von rechts nach dem 'O' fuer fehleranalyse extrahieren
	error=${meldung##*O}
	if [ "$error" != "hne_Fehler_beendet" ]
		then
		echo "$meldung" | zenity --title="Normalisierungsfehler " --text-info --width=500 --height=200
	fi

) | zenity --progress \
           --title="Datei bearbeiten" --text="..." --width=500 --pulsate --auto-close

if [ "$?" = -1 ] ; then
	zenity --error --text="Bearbeitung abgebrochen"
fi
done
exit
